import { AIChatBox, Message } from "@/components/AIChatBox";
import { PageHeading, SectionCard } from "@/components/herp/HerpUI";
import { trpc } from "@/lib/trpc";
import { Bot, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Assistant() {
  const [messages, setMessages] = useState<Message[]>([]);
  const ask = trpc.herp.ai.ask.useMutation({ onSuccess: (response) => setMessages((previous) => [...previous, { role: "assistant", content: typeof response.answer === "string" ? response.answer : JSON.stringify(response.answer) }]), onError: (error) => { toast.error(error.message); setMessages((previous) => [...previous, { role: "assistant", content: "تعذر الوصول إلى المساعد الآن. حاول مرة أخرى لاحقًا." }]); } });
  const send = (question: string) => { setMessages((previous) => [...previous, { role: "user", content: question }]); ask.mutate({ question }); };
  return <div className="animate-herp-in"><PageHeading eyebrow="HERP INTELLIGENCE" title="مساعد HERP الذكي" description="اسأل بلغة طبيعية عن المؤشرات المتاحة، واتخذ قراراتك بناءً على بيانات مؤسستك الحالية." /><div className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><AIChatBox messages={messages} onSendMessage={send} isLoading={ask.isPending} height="640px" placeholder="مثال: ما إجمالي المبيعات المسجلة؟" emptyStateMessage="كيف يمكنني مساعدتك في قراءة أداء مؤسستك؟" suggestedPrompts={["ما إجمالي المبيعات المسجلة؟", "هل يوجد تنبيه للمخزون الحرج؟", "كم عدد الموظفين النشطين؟", "ما أبرز نقاط المتابعة الآن؟"]} className="border-white/[0.08] bg-[#0d1728] shadow-none" /><div className="space-y-5"><SectionCard title="نطاق المساعد" subtitle="ضوابط استخدام شفافة"><div className="space-y-4"><div className="flex gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-cyan-400/10 text-cyan-300"><Bot className="size-4" /></div><p className="text-sm leading-6 text-slate-400">يعتمد المساعد على ملخصات مؤشرات HERP الحالية، ويجيب بالعربية وبصورة موجزة.</p></div><div className="flex gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-emerald-400/10 text-emerald-300"><ShieldCheck className="size-4" /></div><p className="text-sm leading-6 text-slate-400">لا يختلق أرقامًا؛ عند عدم توفر البيانات، يصرّح بذلك بدل تقديم تخمين.</p></div></div></SectionCard><SectionCard title="أسئلة مقترحة"><div className="space-y-2">{["ما إجمالي المبيعات هذا الشهر؟", "هل توجد فواتير أو مهام تستحق المتابعة؟", "كم تبلغ قيمة المخزون؟"].map((prompt) => <button key={prompt} onClick={() => send(prompt)} disabled={ask.isPending} className="w-full rounded-xl border border-white/[0.06] bg-white/[0.02] p-3 text-right text-sm text-slate-300 transition-colors hover:bg-white/[0.06] disabled:opacity-50">{prompt}</button>)}</div></SectionCard></div></div></div>;
}
