import { CreateDialog, EmptyState, FormInput, FormSelect, PageHeading, SectionCard, StatusBadge } from "@/components/herp/HerpUI";
import { trpc } from "@/lib/trpc";
import { BriefcaseBusiness, CalendarClock, CircleUserRound, Handshake } from "lucide-react";
import { toast } from "sonner";

const money = (value: number) => new Intl.NumberFormat("ar-SA", { style: "currency", currency: "SAR", maximumFractionDigits: 0 }).format(value || 0);
const date = (value: Date | string | null) => value ? new Date(value).toLocaleDateString("ar-SA", { year: "numeric", month: "short", day: "numeric" }) : "—";

export default function CRM() {
  const utils = trpc.useUtils();
  const clients = trpc.herp.crm.clients.useQuery();
  const opportunities = trpc.herp.crm.opportunities.useQuery();
  const followUps = trpc.herp.crm.followUps.useQuery();
  const addClient = trpc.herp.crm.createClient.useMutation({ onSuccess: () => { toast.success("تمت إضافة العميل."); utils.herp.crm.clients.invalidate(); utils.herp.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  const addOpportunity = trpc.herp.crm.createOpportunity.useMutation({ onSuccess: () => { toast.success("تمت إضافة فرصة البيع."); utils.herp.crm.opportunities.invalidate(); }, onError: (error) => toast.error(error.message) });
  const addFollowUp = trpc.herp.crm.createFollowUp.useMutation({ onSuccess: () => { toast.success("تمت جدولة المتابعة."); utils.herp.crm.followUps.invalidate(); utils.herp.notifications.list.invalidate(); }, onError: (error) => toast.error(error.message) });
  const pipelineValue = opportunities.data?.filter((item) => !["lost", "won"].includes(item.stage)).reduce((sum, item) => sum + item.estimatedValue, 0) ?? 0;
  return <div className="animate-herp-in"><PageHeading eyebrow="CUSTOMER RELATIONSHIPS" title="إدارة علاقات العملاء" description="قاعدة العملاء، ومسار فرص المبيعات، والمتابعات التي تحفظ سياق العلاقة." action={<CreateDialog title="إضافة عميل" description="أضف بيانات العميل أو العميل المحتمل." triggerLabel="عميل جديد" onSubmit={(form) => addClient.mutate({ name: String(form.name || ""), companyName: String(form.companyName || ""), email: String(form.email || ""), phone: String(form.phone || ""), status: String(form.status || "lead") as "lead" | "active" | "inactive" })} disabled={addClient.isPending}>{(form, setForm) => <><FormInput form={form} setForm={setForm} name="name" label="اسم جهة الاتصال" required /><FormInput form={form} setForm={setForm} name="companyName" label="اسم الشركة" /><div className="grid gap-4 sm:grid-cols-2"><FormInput form={form} setForm={setForm} name="email" label="البريد الإلكتروني" type="email" /><FormInput form={form} setForm={setForm} name="phone" label="الجوال" /></div><FormSelect form={form} setForm={setForm} name="status" label="حالة العميل" options={[{ value: "lead", label: "عميل محتمل" }, { value: "active", label: "عميل نشط" }, { value: "inactive", label: "غير نشط" }]} /></>}</CreateDialog>} />
    <div className="grid gap-4 sm:grid-cols-3"><div className="herp-mini-card"><CircleUserRound className="size-5 text-cyan-300" /><div><p className="text-2xl font-bold text-white">{clients.data?.length ?? 0}</p><p>جهات اتصال</p></div></div><div className="herp-mini-card"><BriefcaseBusiness className="size-5 text-violet-300" /><div><p className="text-2xl font-bold text-white">{opportunities.data?.length ?? 0}</p><p>فرص مبيعات</p></div></div><div className="herp-mini-card"><Handshake className="size-5 text-emerald-300" /><div><p className="text-2xl font-bold text-white">{money(pipelineValue)}</p><p>قيمة خط الأنابيب</p></div></div></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_0.75fr]"><SectionCard title="قاعدة العملاء" subtitle="معلومات الاتصال والحالة التجارية الحالية">{clients.isLoading ? <div className="herp-loading">جارٍ تحميل العملاء…</div> : clients.data?.length ? <div className="overflow-x-auto"><table className="herp-table min-w-[680px]"><thead><tr><th>العميل</th><th>وسيلة الاتصال</th><th>الحالة</th></tr></thead><tbody>{clients.data.map((client) => <tr key={client.id}><td><p className="font-semibold text-slate-200">{client.name}</p><p className="mt-1 text-xs text-slate-500">{client.companyName || "فرد / جهة مستقلة"}</p></td><td><p>{client.phone || "—"}</p><p className="mt-1 text-xs text-slate-500">{client.email || "—"}</p></td><td><StatusBadge value={client.status} /></td></tr>)}</tbody></table></div> : <EmptyState icon={CircleUserRound} title="لا يوجد عملاء بعد" description="ابدأ بإضافة العملاء المحتملين أو الجهات الحالية." />}</SectionCard>
      <SectionCard title="إجراء سريع" subtitle="إضافة فرصة مرتبطة بعميل" action={clients.data?.length ? <CreateDialog title="فرصة بيع" description="أضف فرصة إلى مسار المبيعات واربطها بعميل." triggerLabel="فرصة جديدة" onSubmit={(form) => addOpportunity.mutate({ clientId: Number(form.clientId), title: String(form.title || ""), estimatedValue: Number(form.estimatedValue || 0), stage: String(form.stage || "qualification") as "qualification" | "proposal" | "negotiation" | "won" | "lost" })} disabled={addOpportunity.isPending}>{(form, setForm) => <><FormSelect form={form} setForm={setForm} name="clientId" label="العميل" options={clients.data.map((client) => ({ value: String(client.id), label: client.name }))} /><FormInput form={form} setForm={setForm} name="title" label="اسم الفرصة" required /><FormInput form={form} setForm={setForm} name="estimatedValue" label="القيمة التقديرية" type="number" min={0} /><FormSelect form={form} setForm={setForm} name="stage" label="المرحلة" options={[{ value: "qualification", label: "تأهيل" }, { value: "proposal", label: "عرض" }, { value: "negotiation", label: "تفاوض" }, { value: "won", label: "مكتسبة" }, { value: "lost", label: "مفقودة" }]} /></>}</CreateDialog> : undefined}>{clients.data?.length ? <CreateDialog title="جدولة متابعة" description="سجل اتصالًا أو اجتماعًا أو ملاحظة للعميل." triggerLabel="متابعة جديدة" onSubmit={(form) => addFollowUp.mutate({ clientId: Number(form.clientId), type: String(form.type || "note") as "call" | "meeting" | "email" | "note", content: String(form.content || ""), dueAt: form.dueAt ? new Date(String(form.dueAt)) : undefined })} disabled={addFollowUp.isPending}>{(form, setForm) => <><FormSelect form={form} setForm={setForm} name="clientId" label="العميل" options={clients.data.map((client) => ({ value: String(client.id), label: client.name }))} /><FormSelect form={form} setForm={setForm} name="type" label="نوع المتابعة" options={[{ value: "call", label: "اتصال" }, { value: "meeting", label: "اجتماع" }, { value: "email", label: "بريد إلكتروني" }, { value: "note", label: "ملاحظة" }]} /><FormInput form={form} setForm={setForm} name="content" label="تفاصيل المتابعة" required /><FormInput form={form} setForm={setForm} name="dueAt" label="تاريخ الاستحقاق" type="date" /></>}</CreateDialog> : <EmptyState icon={Handshake} title="أضف عميلًا أولًا" description="تحتاج الفرص والمتابعات إلى عميل مرتبط." />}</SectionCard></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><SectionCard title="خط أنابيب المبيعات" subtitle="الفرص المسجلة بحسب مرحلتها">{opportunities.data?.length ? <div className="space-y-3">{opportunities.data.map((opportunity) => <div key={opportunity.id} className="flex items-center gap-3 rounded-xl border border-white/[0.06] bg-white/[0.02] p-3"><div className="flex size-9 items-center justify-center rounded-xl bg-violet-300/10 text-violet-300"><BriefcaseBusiness className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate font-semibold text-slate-200">{opportunity.title}</p><p className="mt-1 text-xs text-slate-500">{opportunity.clientName} · {money(opportunity.estimatedValue)}</p></div><StatusBadge value={opportunity.stage} /></div>)}</div> : <EmptyState icon={BriefcaseBusiness} title="لا توجد فرص مبيعات" description="أنشئ فرصًا مرتبطة بعملائك لتتبع خط المبيعات." />}</SectionCard>
      <SectionCard title="سجل المتابعات" subtitle="الأنشطة والالتزامات القادمة">{followUps.data?.length ? <div className="space-y-3">{followUps.data.map((followUp) => <div key={followUp.id} className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-3"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-slate-200">{followUp.clientName}</p><span className="text-xs font-semibold text-cyan-300">{followUp.type === "call" ? "اتصال" : followUp.type === "meeting" ? "اجتماع" : followUp.type === "email" ? "بريد" : "ملاحظة"}</span></div><p className="mt-2 text-sm leading-6 text-slate-400">{followUp.content}</p><p className="mt-2 text-xs text-slate-500"><CalendarClock className="ml-1 inline size-3.5" />{date(followUp.dueAt)}</p></div>)}</div> : <EmptyState icon={CalendarClock} title="لا توجد متابعات" description="سجّل أول متابعة للحفاظ على تاريخ العلاقة مع العميل." />}</SectionCard></div>
  </div>;
}
