import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { EmptyState, PageHeading, SectionCard, StatusBadge } from "@/components/herp/HerpUI";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowUpLeft, BadgeDollarSign, Boxes, ClipboardList, FilePlus2, ReceiptText, UsersRound, WalletCards } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useLocation } from "wouter";

const money = (value: number, currency: string) => new Intl.NumberFormat("ar-SA", { style: "currency", currency, maximumFractionDigits: 0 }).format(value || 0);
const date = (value: Date | string | null) => value ? new Date(value).toLocaleDateString("ar-SA", { year: "numeric", month: "short", day: "numeric" }) : "—";

function MetricCard({ icon: Icon, label, value, note, tone = "cyan" }: { icon: typeof WalletCards; label: string; value: string; note: string; tone?: "cyan" | "violet" | "emerald" | "amber" }) {
  const colors = { cyan: "from-cyan-300/15 to-cyan-300/[0.02] text-cyan-300", violet: "from-violet-300/15 to-violet-300/[0.02] text-violet-300", emerald: "from-emerald-300/15 to-emerald-300/[0.02] text-emerald-300", amber: "from-amber-300/15 to-amber-300/[0.02] text-amber-200" };
  return <div className={`rounded-2xl border border-white/[0.07] bg-gradient-to-br ${colors[tone].split(" text-")[0]} p-5`}><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-400">{label}</p><p className="mt-3 text-2xl font-bold tracking-tight text-white">{value}</p></div><div className={`flex size-10 items-center justify-center rounded-xl bg-white/[0.06] ${colors[tone].split(" ").slice(-1)[0]}`}><Icon className="size-5" /></div></div><p className="mt-4 text-xs text-slate-500">{note}</p></div>;
}

export default function Dashboard() {
  const [_, setLocation] = useLocation();
  const dashboard = trpc.herp.dashboard.useQuery(undefined, { refetchInterval: 60_000 });
  if (dashboard.isLoading) return <DashboardSkeleton />;
  if (dashboard.isError || !dashboard.data) return <EmptyState icon={AlertTriangle} title="تعذر تحميل لوحة القيادة" description={dashboard.error?.message || "تحقق من اتصال قاعدة البيانات وحاول مرة أخرى."} action={<Button onClick={() => dashboard.refetch()}>إعادة المحاولة</Button>} />;
  const { kpis, workspace, tasks, alerts, recentInvoices, salesTrend } = dashboard.data;
  const uncompleted = tasks.filter((task) => task.status !== "completed").length;
  return <div className="animate-herp-in"><PageHeading eyebrow="الرؤية التنفيذية" title={`مرحبًا بك في ${workspace.organizationName}`} description="متابعة مباشرة لأداء أعمالك، والتنبيهات التي تحتاج إلى قرار أو متابعة الآن." action={<Button onClick={() => setLocation("/finance")} className="gap-2 bg-cyan-400 text-slate-950 hover:bg-cyan-300"><FilePlus2 className="size-4" />فاتورة جديدة</Button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={WalletCards} label="إيرادات المبيعات" value={money(kpis.sales, workspace.baseCurrency)} note="إجمالي الفواتير غير الملغاة" tone="cyan" /><MetricCard icon={UsersRound} label="الموظفون النشطون" value={String(kpis.employees)} note="ضمن حالة العمل النشطة" tone="violet" /><MetricCard icon={Boxes} label="قيمة المخزون" value={money(kpis.inventoryValue, workspace.baseCurrency)} note="على أساس رصيد الصنف وسعر البيع" tone="emerald" /><MetricCard icon={BadgeDollarSign} label="العملاء النشطون" value={String(kpis.activeClients)} note="عملاء بعلاقات تجارية نشطة" tone="amber" /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.55fr_0.85fr]"><SectionCard title="اتجاه المبيعات" subtitle="قيمة فواتير المبيعات حسب الفترة المسجلة" action={<button onClick={() => setLocation("/reports")} className="text-xs font-semibold text-cyan-300 hover:text-cyan-200">التقارير التفصيلية</button>}><div className="h-72" dir="ltr">{salesTrend.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={salesTrend} margin={{ top: 12, right: 6, left: -20, bottom: 0 }}><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22d3ee" stopOpacity={0.35} /><stop offset="100%" stopColor="#22d3ee" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid stroke="#ffffff" strokeOpacity={0.06} vertical={false} /><XAxis dataKey="period" tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip cursor={{ stroke: "#22d3ee", strokeOpacity: 0.25 }} contentStyle={{ background: "#111c2f", border: "1px solid rgba(255,255,255,.1)", borderRadius: 12, color: "#e2e8f0" }} formatter={(value) => money(Number(value), workspace.baseCurrency)} /><Area type="monotone" dataKey="value" stroke="#22d3ee" strokeWidth={2.5} fill="url(#salesFill)" /></AreaChart></ResponsiveContainer> : <EmptyState icon={ReceiptText} title="لا توجد مبيعات مسجلة بعد" description="أضف فواتير مبيعات من وحدة المالية، وسيظهر الاتجاه الزمني هنا تلقائيًا." action={<Button variant="outline" onClick={() => setLocation("/finance")} className="border-white/10 bg-transparent text-slate-200 hover:bg-white/5 hover:text-white">فتح المالية</Button>} />}</div></SectionCard>
      <SectionCard title="تتطلب انتباهك" subtitle="تنبيهات مشتقة من الحالات التشغيلية الحالية"><div className="space-y-3">{alerts.length ? alerts.map((alert) => <button onClick={() => setLocation(`/${alert!.moduleKey === "finance" ? "finance" : alert!.moduleKey}`)} key={`${alert!.type}-${alert!.title}`} className="flex w-full items-center gap-3 rounded-xl border border-white/[0.06] bg-white/[0.025] p-3 text-right transition-colors hover:bg-white/[0.055]"><div className="flex size-9 items-center justify-center rounded-xl bg-amber-300/10 text-amber-200"><AlertTriangle className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-200">{alert!.title}</p><p className="mt-1 text-xs text-slate-500">راجع الوحدة ذات الصلة لاتخاذ الإجراء.</p></div><span className="rounded-lg bg-amber-300/10 px-2 py-1 text-sm font-bold text-amber-200">{alert!.count}</span></button>) : <EmptyState icon={ArrowUpLeft} title="لا توجد تنبيهات حرجة" description="ستظهر هنا الفواتير المتأخرة، المخزون الحرج وطلبات الإجازة." />}</div></SectionCard></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><SectionCard title="المهام المفتوحة" subtitle={`${uncompleted} مهمة تحتاج متابعة`} action={<button onClick={() => setLocation("/tasks")} className="text-xs font-semibold text-cyan-300 hover:text-cyan-200">عرض الكل</button>}>{tasks.length ? <div className="divide-y divide-white/[0.06]">{tasks.map((task) => <div key={task.id} className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><div className={`size-2 shrink-0 rounded-full ${task.priority === "critical" ? "bg-rose-400" : task.priority === "high" ? "bg-amber-300" : "bg-cyan-300"}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-200">{task.title}</p><p className="mt-1 text-xs text-slate-500">{task.moduleKey} · {date(task.dueAt)}</p></div><StatusBadge value={task.status} /></div>)}</div> : <EmptyState icon={ClipboardList} title="لا توجد مهام مفتوحة" description="يمكنك إنشاء مهمة من مركز المهام وربطها بوحدة معينة." action={<Button variant="outline" onClick={() => setLocation("/tasks")} className="border-white/10 bg-transparent text-slate-200 hover:bg-white/5 hover:text-white">إدارة المهام</Button>} />}</SectionCard>
      <SectionCard title="آخر الفواتير" subtitle="سجل أحدث المستندات المالية" action={<button onClick={() => setLocation("/finance")} className="text-xs font-semibold text-cyan-300 hover:text-cyan-200">فتح الفواتير</button>}>{recentInvoices.length ? <div className="overflow-x-auto"><table className="w-full min-w-[520px] text-right"><thead><tr className="border-b border-white/[0.06] text-xs font-medium text-slate-500"><th className="pb-3">الرقم</th><th className="pb-3">التاريخ</th><th className="pb-3">الإجمالي</th><th className="pb-3">الحالة</th></tr></thead><tbody>{recentInvoices.map((invoice) => <tr key={invoice.id} className="border-b border-white/[0.05] last:border-0"><td className="py-3 text-sm font-semibold text-slate-200">{invoice.invoiceNumber}</td><td className="py-3 text-xs text-slate-500">{date(invoice.issueDate)}</td><td className="py-3 text-sm text-slate-300">{money(invoice.totalAmount, workspace.baseCurrency)}</td><td className="py-3"><StatusBadge value={invoice.status} /></td></tr>)}</tbody></table></div> : <EmptyState icon={ReceiptText} title="لا توجد فواتير بعد" description="أضف أول فاتورة مبيعات أو مشتريات لتظهر ضمن لوحة القيادة." action={<Button variant="outline" onClick={() => setLocation("/finance")} className="border-white/10 bg-transparent text-slate-200 hover:bg-white/5 hover:text-white">إضافة فاتورة</Button>} />}</SectionCard></div>
  </div>;
}

function DashboardSkeleton() { return <div className="space-y-6"><div className="space-y-3"><Skeleton className="h-4 w-24 bg-white/5" /><Skeleton className="h-10 w-72 bg-white/5" /><Skeleton className="h-5 w-full max-w-xl bg-white/5" /></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-40 rounded-2xl bg-white/5" />)}</div><div className="grid gap-5 xl:grid-cols-2"><Skeleton className="h-80 rounded-2xl bg-white/5" /><Skeleton className="h-80 rounded-2xl bg-white/5" /></div></div>; }
