import { CreateDialog, EmptyState, FormInput, FormSelect, PageHeading, SectionCard, StatusBadge } from "@/components/herp/HerpUI";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, Landmark, ReceiptText, Scale, WalletCards } from "lucide-react";
import { toast } from "sonner";

const money = (value: number) => new Intl.NumberFormat("ar-SA", { style: "currency", currency: "SAR", maximumFractionDigits: 0 }).format(value || 0);
const date = (value: Date | string | null) => value ? new Date(value).toLocaleDateString("ar-SA") : "—";

export default function Finance() {
  const utils = trpc.useUtils();
  const invoices = trpc.herp.finance.invoices.useQuery();
  const accounts = trpc.herp.finance.accounts.useQuery();
  const journals = trpc.herp.finance.journals.useQuery();
  const trialBalance = trpc.herp.finance.trialBalance.useQuery();
  const incomeStatement = trpc.herp.finance.incomeStatement.useQuery();
  const addInvoice = trpc.herp.finance.createInvoice.useMutation({ onSuccess: () => { toast.success("تم إنشاء الفاتورة."); utils.herp.finance.invoices.invalidate(); utils.herp.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  const addAccount = trpc.herp.finance.createAccount.useMutation({ onSuccess: () => { toast.success("تمت إضافة الحساب."); utils.herp.finance.accounts.invalidate(); utils.herp.finance.trialBalance.invalidate(); }, onError: (error) => toast.error(error.message) });
  const addJournal = trpc.herp.finance.createJournal.useMutation({ onSuccess: () => { toast.success("تم ترحيل القيد بنجاح."); utils.herp.finance.journals.invalidate(); utils.herp.finance.trialBalance.invalidate(); }, onError: (error) => toast.error(error.message) });
  const due = invoices.data?.filter((invoice) => invoice.status === "overdue" || invoice.status === "sent").reduce((sum, invoice) => sum + invoice.totalAmount - invoice.paidAmount, 0) ?? 0;
  const debitTotal = trialBalance.data?.reduce((sum, item) => sum + item.debit, 0) ?? 0;
  const creditTotal = trialBalance.data?.reduce((sum, item) => sum + item.credit, 0) ?? 0;
  const accountOptions = accounts.data?.map((account) => ({ value: String(account.id), label: `${account.accountCode} — ${account.accountName}` })) ?? [];
  return <div className="animate-herp-in"><PageHeading eyebrow="FINANCE CONTROL" title="المالية والمحاسبة" description="الفواتير، ودليل الحسابات، والقيود اليومية وميزان المراجعة." action={<CreateDialog title="فاتورة جديدة" description="أنشئ فاتورة مبيعات أو مشتريات لتظهر في لوحة القيادة والتقارير." triggerLabel="فاتورة جديدة" onSubmit={(form) => addInvoice.mutate({ invoiceNumber: String(form.invoiceNumber || ""), invoiceType: String(form.invoiceType || "sales") as "sales" | "purchase", totalAmount: Number(form.totalAmount || 0) })} disabled={addInvoice.isPending}>{(form, setForm) => <><FormInput form={form} setForm={setForm} name="invoiceNumber" label="رقم الفاتورة" placeholder="INV-2026-001" required /><FormSelect form={form} setForm={setForm} name="invoiceType" label="نوع الفاتورة" options={[{ value: "sales", label: "مبيعات" }, { value: "purchase", label: "مشتريات" }]} /><FormInput form={form} setForm={setForm} name="totalAmount" label="إجمالي الفاتورة" type="number" min={0} required /></>}</CreateDialog>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="herp-mini-card"><ReceiptText className="size-5 text-cyan-300" /><div><p className="text-2xl font-bold text-white">{invoices.data?.length ?? 0}</p><p>إجمالي الفواتير</p></div></div><div className="herp-mini-card"><WalletCards className="size-5 text-amber-200" /><div><p className="text-2xl font-bold text-white">{money(due)}</p><p>رصيد قيد المتابعة</p></div></div><div className="herp-mini-card"><BookOpenCheck className="size-5 text-violet-300" /><div><p className="text-2xl font-bold text-white">{journals.data?.length ?? 0}</p><p>قيود مرحّلة</p></div></div><div className="herp-mini-card"><Scale className="size-5 text-emerald-300" /><div><p className="text-2xl font-bold text-white">{money(incomeStatement.data?.netIncome ?? 0)}</p><p>صافي الدخل</p></div></div></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_0.75fr]"><SectionCard title="الفواتير" subtitle="متابعة الفواتير المباعة والمشتراة">{invoices.isLoading ? <div className="herp-loading">جارٍ تحميل الفواتير…</div> : invoices.data?.length ? <div className="overflow-x-auto"><table className="herp-table min-w-[700px]"><thead><tr><th>الرقم</th><th>النوع</th><th>الإصدار</th><th>الإجمالي</th><th>الحالة</th></tr></thead><tbody>{invoices.data.map((invoice) => <tr key={invoice.id}><td className="font-semibold text-slate-200">{invoice.invoiceNumber}<p className="mt-1 text-xs text-slate-500">{invoice.clientName || "بدون عميل مرتبط"}</p></td><td><StatusBadge value={invoice.invoiceType} /></td><td>{date(invoice.issueDate)}</td><td className="font-medium text-slate-200">{money(invoice.totalAmount)}</td><td><StatusBadge value={invoice.status} /></td></tr>)}</tbody></table></div> : <EmptyState icon={ReceiptText} title="لا توجد فواتير مسجلة" description="أنشئ أول فاتورة لبدء متابعة الإيرادات والذمم." />}</SectionCard>
      <SectionCard title="دليل الحسابات" subtitle="هيكل الحسابات الأساسي للمؤسسة" action={<CreateDialog title="إضافة حساب" description="أضف حسابًا إلى دليل حسابات مؤسستك." triggerLabel="حساب" onSubmit={(form) => addAccount.mutate({ accountCode: String(form.accountCode || ""), accountName: String(form.accountName || ""), accountType: String(form.accountType || "asset") as "asset" | "liability" | "equity" | "revenue" | "expense" })} disabled={addAccount.isPending}>{(form, setForm) => <><FormInput form={form} setForm={setForm} name="accountCode" label="رمز الحساب" required /><FormInput form={form} setForm={setForm} name="accountName" label="اسم الحساب" required /><FormSelect form={form} setForm={setForm} name="accountType" label="تصنيف الحساب" options={[{ value: "asset", label: "أصول" }, { value: "liability", label: "التزامات" }, { value: "equity", label: "حقوق ملكية" }, { value: "revenue", label: "إيرادات" }, { value: "expense", label: "مصروفات" }]} /></>}</CreateDialog>}>{accounts.data?.length ? <div className="space-y-2">{accounts.data.map((account) => <div key={account.id} className="flex items-center justify-between rounded-xl border border-white/[0.06] bg-white/[0.02] p-3"><div><p className="font-semibold text-slate-200">{account.accountName}</p><p className="mt-1 text-xs text-slate-500">{account.accountCode}</p></div><span className="text-xs font-semibold text-cyan-300">{account.accountType}</span></div>)}</div> : <EmptyState icon={Landmark} title="دليل الحسابات فارغ" description="أضف حسابات الأصول والإيرادات والمصروفات." />}</SectionCard></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><SectionCard title="القيود اليومية" subtitle="قيد مبسّط بطرف مدين ودائن متساويين" action={accountOptions.length >= 2 ? <CreateDialog title="قيد يومية جديد" description="ينشر القيد فورًا بعد تحقق التوازن بين المدين والدائن." triggerLabel="قيد جديد" onSubmit={(form) => addJournal.mutate({ entryNumber: String(form.entryNumber || ""), entryDate: new Date(String(form.entryDate)), description: String(form.description || ""), lines: [{ accountId: Number(form.debitAccount), debit: Number(form.amount || 0), credit: 0 }, { accountId: Number(form.creditAccount), debit: 0, credit: Number(form.amount || 0) }] })} disabled={addJournal.isPending}>{(form, setForm) => <><FormInput form={form} setForm={setForm} name="entryNumber" label="رقم القيد" placeholder="JE-2026-001" required /><FormInput form={form} setForm={setForm} name="entryDate" label="تاريخ القيد" type="date" required /><FormInput form={form} setForm={setForm} name="description" label="البيان" required /><FormSelect form={form} setForm={setForm} name="debitAccount" label="الحساب المدين" options={accountOptions} /><FormSelect form={form} setForm={setForm} name="creditAccount" label="الحساب الدائن" options={accountOptions} /><FormInput form={form} setForm={setForm} name="amount" label="المبلغ" type="number" min={0.01} required /></>}</CreateDialog> : undefined}>{journals.data?.length ? <div className="space-y-2">{journals.data.map((entry) => <div key={entry.id} className="flex items-center justify-between rounded-xl border border-white/[0.06] bg-white/[0.02] p-3"><div><p className="font-semibold text-slate-200">{entry.entryNumber}</p><p className="mt-1 text-xs text-slate-500">{entry.description} · {date(entry.entryDate)}</p></div><StatusBadge value={entry.status} /></div>)}</div> : <EmptyState icon={BookOpenCheck} title="لا توجد قيود بعد" description={accountOptions.length < 2 ? "أضف حسابين على الأقل لتسجيل قيد يومية." : "أضف أول قيد يومية متوازن."} />}</SectionCard>
      <SectionCard title="ميزان المراجعة وقائمة الدخل" subtitle={`المدين ${money(debitTotal)} · الدائن ${money(creditTotal)} · الإيرادات ${money(incomeStatement.data?.revenue ?? 0)} · المصروفات ${money(incomeStatement.data?.expenses ?? 0)}`}>{trialBalance.data?.length ? <div className="overflow-x-auto"><table className="herp-table min-w-[560px]"><thead><tr><th>الحساب</th><th>مدين</th><th>دائن</th></tr></thead><tbody>{trialBalance.data.map((row) => <tr key={row.id}><td><p className="font-semibold text-slate-200">{row.accountName}</p><p className="mt-1 text-xs text-slate-500">{row.accountCode}</p></td><td>{money(row.debit)}</td><td>{money(row.credit)}</td></tr>)}</tbody></table></div> : <EmptyState icon={Scale} title="لا توجد أرصدة بعد" description="ستظهر الأرصدة بعد إضافة الحسابات وترحيل القيود." />}</SectionCard></div>
  </div>;
}
