import { Button } from "@/components/ui/button";
import { CreateDialog, EmptyState, FormInput, FormSelect, PageHeading, SectionCard, StatusBadge } from "@/components/herp/HerpUI";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Check, ClipboardCheck, Clock3, PlusCircle, UsersRound, WalletCards } from "lucide-react";
import { toast } from "sonner";

const date = (value: Date | string | null) => value ? new Date(value).toLocaleDateString("ar-SA", { year: "numeric", month: "short", day: "numeric" }) : "—";
const money = (value: number) => new Intl.NumberFormat("ar-SA", { style: "currency", currency: "SAR", maximumFractionDigits: 0 }).format(value || 0);

export default function HumanResources() {
  const utils = trpc.useUtils();
  const employees = trpc.herp.people.list.useQuery();
  const leaves = trpc.herp.people.leaves.useQuery();
  const attendance = trpc.herp.people.attendance.useQuery();
  const payrolls = trpc.herp.people.payrolls.useQuery();
  const addEmployee = trpc.herp.people.create.useMutation({ onSuccess: () => { toast.success("تمت إضافة الموظف."); utils.herp.people.list.invalidate(); utils.herp.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  const createLeave = trpc.herp.people.createLeave.useMutation({ onSuccess: () => { toast.success("تم تسجيل طلب الإجازة."); utils.herp.people.leaves.invalidate(); utils.herp.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  const reviewLeave = trpc.herp.people.reviewLeave.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة الطلب."); utils.herp.people.leaves.invalidate(); utils.herp.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  const recordAttendance = trpc.herp.people.recordAttendance.useMutation({ onSuccess: () => { toast.success("تم تسجيل الحضور."); utils.herp.people.attendance.invalidate(); }, onError: (error) => toast.error(error.message) });
  const createPayroll = trpc.herp.people.createPayroll.useMutation({ onSuccess: () => { toast.success("تم إنشاء مسير الرواتب كمسودة."); utils.herp.people.payrolls.invalidate(); }, onError: (error) => toast.error(error.message) });
  const activeEmployees = employees.data?.filter((item) => item.employmentStatus === "active").length ?? 0;
  const pendingLeaves = leaves.data?.filter((item) => item.status === "pending").length ?? 0;
  const presentCount = attendance.data?.filter((item) => item.status === "present" || item.status === "late" || item.status === "remote").length ?? 0;
  return <div className="animate-herp-in"><PageHeading eyebrow="HUMAN CAPITAL" title="الموارد البشرية" description="قاعدة موحّدة للموظفين والحضور والإجازات ومسيرات الرواتب." action={<CreateDialog title="إضافة موظف" description="أدخل البيانات الأساسية للموظف الجديد." triggerLabel="موظف جديد" onSubmit={(form) => addEmployee.mutate({ fullName: String(form.fullName || ""), jobTitle: String(form.jobTitle || ""), employeeCode: String(form.employeeCode || ""), email: String(form.email || ""), phone: String(form.phone || ""), baseSalary: Number(form.baseSalary || 0) })} disabled={addEmployee.isPending}>{(form, setForm) => <><FormInput form={form} setForm={setForm} name="fullName" label="الاسم الكامل" required /><FormInput form={form} setForm={setForm} name="employeeCode" label="الرقم الوظيفي" placeholder="EMP-001" required /><FormInput form={form} setForm={setForm} name="jobTitle" label="المسمى الوظيفي" required /><div className="grid gap-4 sm:grid-cols-2"><FormInput form={form} setForm={setForm} name="email" label="البريد الإلكتروني" type="email" /><FormInput form={form} setForm={setForm} name="phone" label="رقم الجوال" /></div><FormInput form={form} setForm={setForm} name="baseSalary" label="الراتب الأساسي" type="number" min={0} /></>}</CreateDialog>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="herp-mini-card"><UsersRound className="size-5 text-cyan-300" /><div><p className="text-2xl font-bold text-white">{activeEmployees}</p><p>موظفون نشطون</p></div></div><div className="herp-mini-card"><ClipboardCheck className="size-5 text-emerald-300" /><div><p className="text-2xl font-bold text-white">{presentCount}</p><p>حضور مسجل</p></div></div><div className="herp-mini-card"><Clock3 className="size-5 text-amber-200" /><div><p className="text-2xl font-bold text-white">{pendingLeaves}</p><p>طلبات معلقة</p></div></div><div className="herp-mini-card"><WalletCards className="size-5 text-violet-300" /><div><p className="text-2xl font-bold text-white">{payrolls.data?.length ?? 0}</p><p>مسيرات رواتب</p></div></div></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_0.85fr]"><SectionCard title="دليل الموظفين" subtitle="كل الموظفين المسجلين ضمن مساحة العمل">{employees.isLoading ? <div className="herp-loading">جارٍ تحميل الموظفين…</div> : employees.data?.length ? <div className="overflow-x-auto"><table className="herp-table min-w-[720px]"><thead><tr><th>الموظف</th><th>المسمى</th><th>الراتب الأساسي</th><th>الحالة</th></tr></thead><tbody>{employees.data.map((employee) => <tr key={employee.id}><td><p className="font-semibold text-slate-200">{employee.fullName}</p><p className="mt-1 text-xs text-slate-500">{employee.employeeCode} {employee.email ? `· ${employee.email}` : ""}</p></td><td>{employee.jobTitle}</td><td>{money(employee.baseSalary)}</td><td><StatusBadge value={employee.employmentStatus} /></td></tr>)}</tbody></table></div> : <EmptyState icon={UsersRound} title="لا يوجد موظفون بعد" description="أضف بيانات فريقك لتبدأ بناء سجل الموارد البشرية." />}</SectionCard>
      <SectionCard title="إجراءات الموارد البشرية" subtitle="اطلب إجازة أو سجّل حضورًا أو أنشئ مسيرًا"><div className="space-y-3">{employees.data?.length ? <><CreateDialog title="طلب إجازة" description="سيظهر الطلب في قائمة المراجعة فورًا." triggerLabel="طلب إجازة" onSubmit={(form) => createLeave.mutate({ employeeId: Number(form.employeeId), leaveType: String(form.leaveType || "annual") as "annual" | "sick" | "unpaid" | "other", startDate: new Date(String(form.startDate)), endDate: new Date(String(form.endDate)), reason: String(form.reason || "") })} disabled={createLeave.isPending}>{(form, setForm) => <><FormSelect form={form} setForm={setForm} name="employeeId" label="الموظف" options={employees.data.map((employee) => ({ value: String(employee.id), label: `${employee.fullName} — ${employee.employeeCode}` }))} /><FormSelect form={form} setForm={setForm} name="leaveType" label="نوع الإجازة" options={[{ value: "annual", label: "سنوية" }, { value: "sick", label: "مرضية" }, { value: "unpaid", label: "بدون راتب" }, { value: "other", label: "أخرى" }]} /><div className="grid gap-4 sm:grid-cols-2"><FormInput form={form} setForm={setForm} name="startDate" label="تاريخ البداية" type="date" required /><FormInput form={form} setForm={setForm} name="endDate" label="تاريخ النهاية" type="date" required /></div><FormInput form={form} setForm={setForm} name="reason" label="السبب" /></>}</CreateDialog><CreateDialog title="تسجيل حضور" description="سجّل حالة حضور موظف ليوم محدد." triggerLabel="تسجيل حضور" onSubmit={(form) => recordAttendance.mutate({ employeeId: Number(form.employeeId), workDate: new Date(String(form.workDate)), status: String(form.status || "present") as "present" | "absent" | "late" | "remote" })} disabled={recordAttendance.isPending}>{(form, setForm) => <><FormSelect form={form} setForm={setForm} name="employeeId" label="الموظف" options={employees.data.map((employee) => ({ value: String(employee.id), label: employee.fullName }))} /><FormInput form={form} setForm={setForm} name="workDate" label="تاريخ العمل" type="date" required /><FormSelect form={form} setForm={setForm} name="status" label="الحالة" options={[{ value: "present", label: "حاضر" }, { value: "late", label: "متأخر" }, { value: "remote", label: "عن بُعد" }, { value: "absent", label: "غائب" }]} /></>}</CreateDialog><CreateDialog title="إنشاء مسير رواتب" description="ينشئ مسودة بإجمالي رواتب الموظفين النشطين." triggerLabel="مسير رواتب" onSubmit={(form) => createPayroll.mutate({ periodLabel: String(form.periodLabel || "") })} disabled={createPayroll.isPending}>{(form, setForm) => <FormInput form={form} setForm={setForm} name="periodLabel" label="فترة المسير" placeholder="أغسطس 2026" required />}</CreateDialog></> : <EmptyState icon={PlusCircle} title="أضف موظفًا أولًا" description="تتطلب العمليات وجود موظف مسجل." />}</div></SectionCard></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><SectionCard title="طلبات الإجازة" subtitle="طلبات تحتاج إلى مراجعة أو حالات الإجازة المعتمدة">{leaves.isLoading ? <div className="herp-loading">جارٍ تحميل الطلبات…</div> : leaves.data?.length ? <div className="overflow-x-auto"><table className="herp-table min-w-[700px]"><thead><tr><th>الموظف</th><th>الفترة</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{leaves.data.map((leave) => <tr key={leave.id}><td className="font-semibold text-slate-200">{leave.fullName}</td><td>{date(leave.startDate)} — {date(leave.endDate)}</td><td><StatusBadge value={leave.status} /></td><td>{leave.status === "pending" ? <div className="flex gap-2"><Button size="sm" onClick={() => reviewLeave.mutate({ id: leave.id, status: "approved" })} className="h-8 bg-emerald-400/10 text-emerald-300 hover:bg-emerald-400/20"><Check className="size-3.5" />اعتماد</Button><Button size="sm" variant="ghost" onClick={() => reviewLeave.mutate({ id: leave.id, status: "rejected" })} className="h-8 text-rose-300 hover:bg-rose-400/10 hover:text-rose-200">رفض</Button></div> : "—"}</td></tr>)}</tbody></table></div> : <EmptyState icon={CalendarDays} title="لا توجد طلبات إجازة" description="ستظهر طلبات الموظفين في هذا القسم." />}</SectionCard>
      <SectionCard title="آخر الحضور ومسيرات الرواتب" subtitle="سجل العمل والتكاليف الشهرية"><div className="space-y-3">{attendance.data?.slice(0, 4).map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border border-white/[0.06] bg-white/[0.02] p-3"><div><p className="text-sm font-semibold text-slate-200">{item.fullName}</p><p className="mt-1 text-xs text-slate-500">{date(item.workDate)}</p></div><StatusBadge value={item.status} /></div>)}{payrolls.data?.slice(0, 3).map((run) => <div key={`payroll-${run.id}`} className="flex items-center justify-between rounded-xl border border-violet-300/[0.1] bg-violet-300/[0.03] p-3"><div><p className="text-sm font-semibold text-slate-200">{run.periodLabel}</p><p className="mt-1 text-xs text-slate-500">مسير رواتب</p></div><span className="text-sm font-bold text-violet-200">{money(run.totalNet)}</span></div>)}{!(attendance.data?.length || payrolls.data?.length) && <EmptyState icon={ClipboardCheck} title="لا توجد سجلات تشغيلية" description="سيظهر الحضور ومسيرات الرواتب هنا." />}</div></SectionCard></div>
  </div>;
}
