import { CreateDialog, EmptyState, FormInput, FormSelect, PageHeading, SectionCard } from "@/components/herp/HerpUI";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowDownToLine, ArrowUpFromLine, Boxes, PackageSearch } from "lucide-react";
import { toast } from "sonner";

export default function Inventory() {
  const utils = trpc.useUtils();
  const products = trpc.herp.inventory.products.useQuery();
  const createProduct = trpc.herp.inventory.createProduct.useMutation({ onSuccess: () => { toast.success("تمت إضافة الصنف."); utils.herp.inventory.products.invalidate(); utils.herp.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  const moveStock = trpc.herp.inventory.moveStock.useMutation({ onSuccess: () => { toast.success("تم تسجيل حركة المخزون."); utils.herp.inventory.products.invalidate(); utils.herp.dashboard.invalidate(); utils.herp.notifications.list.invalidate(); }, onError: (error) => toast.error(error.message) });
  const lowStock = products.data?.filter((product) => product.quantityOnHand <= product.reorderLevel).length ?? 0;
  return <div className="animate-herp-in"><PageHeading eyebrow="SUPPLY & WAREHOUSE" title="المخزون والمستودعات" description="إدارة الأصناف، والأرصدة المتاحة، وتنبيهات حد إعادة الطلب." action={<CreateDialog title="إضافة صنف" description="أدخل بيانات الصنف ورصيد البداية وحد إعادة الطلب." triggerLabel="صنف جديد" onSubmit={(form) => createProduct.mutate({ sku: String(form.sku || ""), name: String(form.name || ""), category: String(form.category || ""), unit: String(form.unit || "قطعة"), salePrice: Number(form.salePrice || 0), quantityOnHand: Number(form.quantityOnHand || 0), reorderLevel: Number(form.reorderLevel || 0) })} disabled={createProduct.isPending}>{(form, setForm) => <><FormInput form={form} setForm={setForm} name="sku" label="رمز الصنف" placeholder="SKU-001" required /><FormInput form={form} setForm={setForm} name="name" label="اسم الصنف" required /><div className="grid gap-4 sm:grid-cols-2"><FormInput form={form} setForm={setForm} name="category" label="الفئة" /><FormInput form={form} setForm={setForm} name="unit" label="وحدة القياس" placeholder="قطعة" /></div><div className="grid gap-4 sm:grid-cols-3"><FormInput form={form} setForm={setForm} name="salePrice" label="سعر البيع" type="number" min={0} /><FormInput form={form} setForm={setForm} name="quantityOnHand" label="رصيد البداية" type="number" min={0} /><FormInput form={form} setForm={setForm} name="reorderLevel" label="حد إعادة الطلب" type="number" min={0} /></div></>}</CreateDialog>} />
    <div className="grid gap-4 sm:grid-cols-3"><div className="herp-mini-card"><Boxes className="size-5 text-cyan-300" /><div><p className="text-2xl font-bold text-white">{products.data?.length ?? 0}</p><p>أصناف مسجلة</p></div></div><div className="herp-mini-card"><AlertTriangle className="size-5 text-amber-200" /><div><p className="text-2xl font-bold text-white">{lowStock}</p><p>تنبيهات مخزون</p></div></div><div className="herp-mini-card"><PackageSearch className="size-5 text-emerald-300" /><div><p className="text-2xl font-bold text-white">{new Intl.NumberFormat("ar-SA", { maximumFractionDigits: 0 }).format(products.data?.reduce((sum, product) => sum + product.quantityOnHand, 0) ?? 0)}</p><p>إجمالي الوحدات</p></div></div></div>
    <SectionCard className="mt-5" title="كتالوج الأصناف" subtitle="الرصيد الحالي يحدّث فور تسجيل حركة مخزون" action={products.data?.length ? <CreateDialog title="حركة مخزون" description="سجل واردًا أو صادرًا أو عدل الرصيد إلى قيمة محددة." triggerLabel="حركة مخزون" onSubmit={(form) => moveStock.mutate({ productId: Number(form.productId), movementType: String(form.movementType || "in") as "in" | "out" | "adjustment", quantity: Number(form.quantity || 0), reference: String(form.reference || "") })} disabled={moveStock.isPending}>{(form, setForm) => <><FormSelect form={form} setForm={setForm} name="productId" label="الصنف" options={products.data.map((product) => ({ value: String(product.id), label: `${product.name} — ${product.sku}` }))} /><FormSelect form={form} setForm={setForm} name="movementType" label="نوع الحركة" options={[{ value: "in", label: "وارد" }, { value: "out", label: "صادر" }, { value: "adjustment", label: "تسوية: تعيين الرصيد" }]} /><FormInput form={form} setForm={setForm} name="quantity" label="الكمية" type="number" min={0} required /><FormInput form={form} setForm={setForm} name="reference" label="مرجع العملية" placeholder="PO-100 / SO-200" /></>}</CreateDialog> : undefined}>{products.isLoading ? <div className="herp-loading">جارٍ تحميل الأصناف…</div> : products.data?.length ? <div className="overflow-x-auto"><table className="herp-table min-w-[760px]"><thead><tr><th>الصنف</th><th>الفئة</th><th>سعر البيع</th><th>الرصيد</th><th>حد الطلب</th><th>الحالة</th></tr></thead><tbody>{products.data.map((product) => { const isLow = product.quantityOnHand <= product.reorderLevel; return <tr key={product.id}><td><p className="font-semibold text-slate-200">{product.name}</p><p className="mt-1 text-xs text-slate-500">{product.sku} · {product.unit}</p></td><td>{product.category || "—"}</td><td>{new Intl.NumberFormat("ar-SA", { style: "currency", currency: "SAR", maximumFractionDigits: 0 }).format(product.salePrice)}</td><td className={isLow ? "font-bold text-amber-200" : "font-semibold text-slate-200"}>{product.quantityOnHand}</td><td>{product.reorderLevel}</td><td>{isLow ? <span className="inline-flex items-center gap-1 text-xs font-semibold text-amber-200"><AlertTriangle className="size-3.5" />بحاجة إعادة طلب</span> : <span className="text-xs font-semibold text-emerald-300">ضمن الحد الآمن</span>}</td></tr>; })}</tbody></table></div> : <EmptyState icon={Boxes} title="كتالوج المخزون فارغ" description="أضف أول صنف، ثم سجّل حركات الوارد والصادر لتتبع الرصيد." />}</SectionCard>
  </div>;
}
