import { Button } from "@/components/ui/button";
import { CreateDialog, EmptyState, FormSelect, PageHeading, SectionCard } from "@/components/herp/HerpUI";
import { trpc } from "@/lib/trpc";
import { BarChart3, CalendarClock, Download, FileSpreadsheet, FileText, Send } from "lucide-react";
import { toast } from "sonner";
import { useState } from "react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";

const money = (value: number, currency: string) => new Intl.NumberFormat("ar-SA", { style: "currency", currency, maximumFractionDigits: 0 }).format(value || 0);

function DownloadReport({ moduleKey, label }: { moduleKey: "finance" | "inventory" | "crm" | "hr"; label: string }) {
  const report = trpc.herp.reports.exportCsv.useQuery({ moduleKey }, { enabled: false });
  const download = async () => { const response = await report.refetch(); if (!response.data) return toast.error("تعذر تجهيز الملف."); const blob = new Blob(["\ufeff" + response.data.content], { type: "text/csv;charset=utf-8" }); const href = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = href; link.download = response.data.filename; link.click(); URL.revokeObjectURL(href); toast.success(`تم تصدير ${label}.`); };
  return <Button variant="outline" disabled={report.isFetching} onClick={download} className="h-auto justify-start gap-3 border-white/[0.07] bg-white/[0.025] px-4 py-4 text-right text-slate-200 hover:bg-white/[0.06] hover:text-white"><div className="flex size-9 items-center justify-center rounded-xl bg-emerald-300/10 text-emerald-300"><FileSpreadsheet className="size-4" /></div><span className="flex-1"><span className="block font-semibold">{label}</span><span className="mt-1 block text-xs font-normal text-slate-500">CSV قابل للفتح في Excel</span></span><Download className="size-4 text-slate-500" /></Button>;
}

export default function Reports() {
  const utils = trpc.useUtils();
  const [period, setPeriod] = useState<"7d" | "30d" | "year">("30d");
  const summary = trpc.herp.reports.summary.useQuery({ period });
  const schedules = trpc.herp.reports.schedules.useQuery();
  const createSchedule = trpc.herp.reports.createSchedule.useMutation({ onSuccess: () => { toast.success("تم حفظ إعداد التقرير. فعّله بعد نشر التطبيق."); utils.herp.reports.schedules.invalidate(); }, onError: (error) => toast.error(error.message) });
  if (summary.isLoading) return <div className="herp-loading min-h-72">جارٍ تحضير مركز التقارير…</div>;
  const data = summary.data;
  return <div className="animate-herp-in"><PageHeading eyebrow="BUSINESS INTELLIGENCE" title="التقارير ومركز الأداء" description="تصدير بيانات الوحدات، وقراءة ملخص الأداء الحالي، وتجهيز ملخصات دورية للمالك." action={<CreateDialog title="إعداد تقرير دوري" description="سيُحفظ الإعداد الآن، ثم يفعّل بعد نشر HERP من خلال مهمة دورية آمنة." triggerLabel="تقرير دوري" onSubmit={(form) => createSchedule.mutate({ name: String(form.name || ""), frequency: String(form.frequency || "weekly") as "daily" | "weekly" })} disabled={createSchedule.isPending}>{(form, setForm) => <><div className="grid gap-2"><label className="text-sm font-semibold text-slate-300">اسم التقرير</label><input value={String(form.name || "")} onChange={(event) => setForm((old) => ({ ...old, name: event.target.value }))} placeholder="ملخص الأداء الأسبوعي" className="h-10 rounded-md border border-white/10 bg-white/[0.04] px-3 text-sm text-slate-100 outline-none focus:ring-2 focus:ring-cyan-400" /></div><FormSelect form={form} setForm={setForm} name="frequency" label="التكرار" options={[{ value: "daily", label: "يومي" }, { value: "weekly", label: "أسبوعي" }]} /></>}</CreateDialog>} />
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/[0.06] bg-white/[0.025] px-4 py-3"><div><p className="text-sm font-semibold text-slate-200">النطاق الزمني للملخص</p><p className="mt-1 text-xs text-slate-500">يُطبّق على الإيرادات والفواتير الأخيرة ومخطط المبيعات.</p></div><div className="flex rounded-xl border border-white/[0.07] bg-slate-950/30 p-1">{([ ["7d", "7 أيام"], ["30d", "30 يومًا"], ["year", "سنة"] ] as const).map(([value, label]) => <button key={value} onClick={() => setPeriod(value)} className={`rounded-lg px-3 py-1.5 text-xs font-semibold transition-colors ${period === value ? "bg-cyan-400 text-slate-950" : "text-slate-400 hover:bg-white/[0.05] hover:text-slate-100"}`}>{label}</button>)}</div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="herp-mini-card"><BarChart3 className="size-5 text-cyan-300" /><div><p className="text-xl font-bold text-white">{money(data?.kpis.sales ?? 0, data?.workspace.baseCurrency || "SAR")}</p><p>إيرادات مبيعات</p></div></div><div className="herp-mini-card"><FileText className="size-5 text-violet-300" /><div><p className="text-2xl font-bold text-white">{data?.kpis.employees ?? 0}</p><p>الموظفون</p></div></div><div className="herp-mini-card"><FileSpreadsheet className="size-5 text-emerald-300" /><div><p className="text-xl font-bold text-white">{money(data?.kpis.inventoryValue ?? 0, data?.workspace.baseCurrency || "SAR")}</p><p>قيمة المخزون</p></div></div><div className="herp-mini-card"><Send className="size-5 text-amber-200" /><div><p className="text-2xl font-bold text-white">{data?.alerts.length ?? 0}</p><p>تنبيهات تشغيلية</p></div></div></div>
    <div className="mt-5"><SectionCard title="اتجاه المبيعات" subtitle="إجمالي الفواتير بحسب الفترة المحددة"><div className="h-56" dir="ltr">{data?.salesTrend.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={data.salesTrend} margin={{ top: 8, right: 8, left: 8, bottom: 0 }}><defs><linearGradient id="herpSalesGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#22d3ee" stopOpacity={0.36} /><stop offset="100%" stopColor="#22d3ee" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="period" tick={{ fill: "#64748b", fontSize: 11 }} tickLine={false} axisLine={false} /><Tooltip formatter={(value: number) => money(value, data.workspace.baseCurrency)} contentStyle={{ background: "#0d1728", border: "1px solid rgba(255,255,255,.1)", borderRadius: 12, color: "#e2e8f0" }} /><Area type="monotone" dataKey="value" stroke="#22d3ee" strokeWidth={2.5} fill="url(#herpSalesGradient)" /></AreaChart></ResponsiveContainer> : <EmptyState icon={BarChart3} title="لا توجد بيانات مبيعات ضمن الفترة" description="غيّر النطاق الزمني أو أضف فواتير مبيعات لعرض الاتجاه." />}</div></SectionCard></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><SectionCard title="تصدير بيانات الوحدات" subtitle="تنزيل مباشرة بصيغة CSV، مع احترام صلاحيات المستخدم الحالية"><div className="grid gap-3 sm:grid-cols-2"><DownloadReport moduleKey="finance" label="الفواتير والمالية" /><DownloadReport moduleKey="inventory" label="المخزون والأصناف" /><DownloadReport moduleKey="crm" label="العملاء وعلاقاتهم" /><DownloadReport moduleKey="hr" label="الموظفون" /></div></SectionCard>
      <SectionCard title="الإرسال الدوري للمالك" subtitle="تجهيز قائمة الملخصات الآلية">{schedules.data?.length ? <div className="space-y-3">{schedules.data.map((schedule) => <div key={schedule.id} className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-3"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-cyan-400/10 text-cyan-300"><CalendarClock className="size-4" /></div><div className="min-w-0 flex-1"><p className="font-semibold text-slate-200">{schedule.name}</p><p className="mt-1 text-xs text-slate-500">تكرار {schedule.frequency === "daily" ? "يومي" : "أسبوعي"}</p></div><span className={`text-xs font-semibold ${schedule.isActive ? "text-emerald-300" : "text-amber-200"}`}>{schedule.isActive ? "مفعّل" : "بانتظار التفعيل"}</span></div>{!schedule.isActive && <p className="mt-3 rounded-lg bg-amber-300/[0.06] px-3 py-2 text-xs leading-5 text-amber-100/70">ينشأ التفعيل بعد نشر التطبيق، لحماية الإرسال من بيئة المعاينة.</p>}</div>)}</div> : <EmptyState icon={CalendarClock} title="لا توجد تقارير دورية" description="أنشئ ملخصًا يوميًا أو أسبوعيًا ليتضمن الوضع المالي والمخزون الحرج والمهام المفتوحة." />}</SectionCard></div>
  </div>;
}
