import { Button } from "@/components/ui/button";
import { CreateDialog, EmptyState, FormInput, FormSelect, PageHeading, SectionCard, StatusBadge } from "@/components/herp/HerpUI";
import { trpc } from "@/lib/trpc";
import { Building2, ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { toast } from "sonner";

const allModules = ["dashboard", "hr", "finance", "inventory", "crm", "reports", "settings"] as const;

export default function Settings() {
  const utils = trpc.useUtils();
  const context = trpc.herp.context.useQuery();
  const members = trpc.herp.members.list.useQuery();
  const addMember = trpc.herp.members.add.useMutation({ onSuccess: () => { toast.success("تمت إضافة العضو للمؤسسة."); utils.herp.members.list.invalidate(); }, onError: (error) => toast.error(error.message) });
  const setRole = trpc.herp.members.setRole.useMutation({ onSuccess: () => { toast.success("تم تحديث صلاحيات العضو."); utils.herp.members.list.invalidate(); }, onError: (error) => toast.error(error.message) });
  const workspace = context.data?.workspace;
  return <div className="animate-herp-in"><PageHeading eyebrow="ORGANIZATION CONTROL" title="الإدارة والصلاحيات" description="إدارة هوية المؤسسة والأدوار والوصول إلى وحدات النظام." action={<CreateDialog title="إضافة عضو" description="يجب أن يسجل العضو دخوله إلى HERP مرة واحدة قبل إضافته. استخدم المعرّف الظاهر لحسابه." triggerLabel="إضافة عضو" onSubmit={(form) => addMember.mutate({ userOpenId: String(form.userOpenId || ""), role: String(form.role || "employee") as "general_manager" | "unit_manager" | "employee", allowedModules: [...allModules] })} disabled={addMember.isPending}>{(form, setForm) => <><FormInput form={form} setForm={setForm} name="userOpenId" label="معرّف المستخدم (Open ID)" placeholder="من حساب العضو داخل HERP" required /><FormSelect form={form} setForm={setForm} name="role" label="الدور" options={[{ value: "employee", label: "موظف" }, { value: "unit_manager", label: "مدير وحدة" }, { value: "general_manager", label: "مدير عام" }]} /></>}</CreateDialog>} />
    <div className="grid gap-5 xl:grid-cols-[0.75fr_1.25fr]"><SectionCard title="هوية المؤسسة" subtitle="المعلومات الأساسية لمساحة العمل"><div className="space-y-4"><div className="flex size-12 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300"><Building2 className="size-6" /></div><div><p className="text-xl font-bold text-white">{workspace?.organizationName || "HERP"}</p><p className="mt-1 text-sm text-slate-500">العملة الأساسية: {workspace?.baseCurrency || "—"}</p></div><div className="rounded-xl bg-white/[0.025] p-3"><p className="text-xs text-slate-500">دورك الحالي</p><p className="mt-1 font-semibold text-cyan-300">{workspace?.memberRole === "general_manager" ? "المدير العام" : workspace?.memberRole === "unit_manager" ? "مدير وحدة" : "موظف"}</p></div><div><p className="mb-2 text-xs text-slate-500">الوحدات المصرح بها</p><div className="flex flex-wrap gap-2">{workspace?.allowedModules.map((module) => <span key={module} className="rounded-lg bg-white/[0.05] px-2.5 py-1 text-xs text-slate-300">{module}</span>)}</div></div></div></SectionCard>
      <SectionCard title="أعضاء المؤسسة" subtitle="الأدوار المستقلة عن حسابات المصادقة العامة">{members.isLoading ? <div className="herp-loading">جارٍ تحميل الأعضاء…</div> : members.data?.length ? <div className="space-y-3">{members.data.map((member) => <div key={member.id} className="flex flex-col gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.02] p-4 sm:flex-row sm:items-center"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-violet-300/10 text-violet-300"><UsersRound className="size-4" /></div><div className="min-w-0 flex-1"><p className="font-semibold text-slate-200">{member.name || "مستخدم بدون اسم"}</p><p className="mt-1 truncate text-xs text-slate-500">{member.email || `المستخدم #${member.userId}`}</p></div><StatusBadge value={member.role} /><select value={member.role} onChange={(event) => setRole.mutate({ memberId: member.id, role: event.target.value as "general_manager" | "unit_manager" | "employee", allowedModules: [...allModules] })} className="h-9 rounded-lg border border-white/10 bg-[#142033] px-2 text-xs text-slate-300 outline-none focus:ring-2 focus:ring-cyan-400"><option value="general_manager">مدير عام</option><option value="unit_manager">مدير وحدة</option><option value="employee">موظف</option></select></div>)}</div> : <EmptyState icon={UserPlus} title="لا يوجد أعضاء بعد" description="أضف أعضاء بعد أن يدخلوا إلى HERP، ثم اضبط أدوارهم وصلاحياتهم." />}</SectionCard></div><div className="mt-5 rounded-2xl border border-cyan-300/10 bg-cyan-300/[0.04] p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-5 text-cyan-300" /><p className="text-sm leading-6 text-slate-400">أدوار HERP داخل المؤسسة هي: المدير العام، ومدير الوحدة، والموظف. يتحكم الدور والصلاحيات المعيّنة في الوحدات المتاحة داخل الواجهة وإجراءات الخادم.</p></div></div>
  </div>;
}
