import { Button } from "@/components/ui/button";
import { CreateDialog, EmptyState, FormInput, FormSelect, PageHeading, SectionCard, StatusBadge } from "@/components/herp/HerpUI";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ClipboardList } from "lucide-react";
import { toast } from "sonner";

const date = (value: Date | string | null) => value ? new Date(value).toLocaleDateString("ar-SA", { year: "numeric", month: "short", day: "numeric" }) : "بدون تاريخ";

export default function Tasks() {
  const utils = trpc.useUtils();
  const tasks = trpc.herp.tasks.list.useQuery();
  const addTask = trpc.herp.tasks.create.useMutation({ onSuccess: () => { toast.success("تم إنشاء المهمة."); utils.herp.tasks.list.invalidate(); utils.herp.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  const updateTask = trpc.herp.tasks.updateStatus.useMutation({ onSuccess: () => { toast.success("تم تحديث المهمة."); utils.herp.tasks.list.invalidate(); utils.herp.dashboard.invalidate(); }, onError: (error) => toast.error(error.message) });
  return <div className="animate-herp-in"><PageHeading eyebrow="WORKFLOW" title="المهام والمتابعات" description="مركز موحّد للمهام التشغيلية المرتبطة بوحدات HERP." action={<CreateDialog title="مهمة جديدة" description="أنشئ مهمة، وحدد الوحدة والأولوية وتاريخ الاستحقاق." triggerLabel="مهمة جديدة" onSubmit={(form) => addTask.mutate({ title: String(form.title || ""), moduleKey: String(form.moduleKey || "dashboard") as "dashboard" | "hr" | "finance" | "inventory" | "crm" | "reports" | "settings", priority: String(form.priority || "medium") as "low" | "medium" | "high" | "critical", dueAt: form.dueAt ? new Date(String(form.dueAt)) : undefined })} disabled={addTask.isPending}>{(form, setForm) => <><FormInput form={form} setForm={setForm} name="title" label="عنوان المهمة" required /><div className="grid gap-4 sm:grid-cols-2"><FormSelect form={form} setForm={setForm} name="moduleKey" label="الوحدة" options={[{ value: "dashboard", label: "الرئيسية" }, { value: "hr", label: "الموارد البشرية" }, { value: "finance", label: "المالية" }, { value: "inventory", label: "المخزون" }, { value: "crm", label: "CRM" }, { value: "reports", label: "التقارير" }, { value: "settings", label: "الإدارة" }]} /><FormSelect form={form} setForm={setForm} name="priority" label="الأولوية" options={[{ value: "low", label: "منخفضة" }, { value: "medium", label: "متوسطة" }, { value: "high", label: "عالية" }, { value: "critical", label: "حرجة" }]} /></div><FormInput form={form} setForm={setForm} name="dueAt" label="تاريخ الاستحقاق" type="date" /></>}</CreateDialog>} />
    <SectionCard title="قائمة العمل" subtitle="استخدم الإنهاء لتحديث حالة المهمة واستبعادها من مؤشرات المتابعة">{tasks.isLoading ? <div className="herp-loading">جارٍ تحميل المهام…</div> : tasks.data?.length ? <div className="space-y-3">{tasks.data.map((task) => <div key={task.id} className="flex flex-col gap-4 rounded-2xl border border-white/[0.07] bg-white/[0.02] p-4 sm:flex-row sm:items-center"><div className={`mt-1 size-2 shrink-0 rounded-full ${task.priority === "critical" ? "bg-rose-400" : task.priority === "high" ? "bg-amber-300" : task.priority === "low" ? "bg-slate-400" : "bg-cyan-300"}`} /><div className="min-w-0 flex-1"><p className="font-semibold text-slate-200">{task.title}</p><p className="mt-1 text-sm text-slate-500">الوحدة: {task.moduleKey} · الاستحقاق: {date(task.dueAt)}</p></div><div className="flex items-center gap-3"><StatusBadge value={task.priority} /><StatusBadge value={task.status} />{task.status !== "completed" && <Button size="sm" onClick={() => updateTask.mutate({ id: task.id, status: "completed" })} className="h-8 gap-1 bg-emerald-400/10 text-emerald-300 hover:bg-emerald-400/20"><CheckCircle2 className="size-3.5" />إنهاء</Button>}</div></div>)}</div> : <EmptyState icon={ClipboardList} title="قائمة المهام فارغة" description="أنشئ المهام التشغيلية ومتابعات الوحدة من هنا." />}</SectionCard>
  </div>;
}
